-- LIMPANDO O CATÁLOGO PARA RE-MATERIALIZAÇÃO COMPLETA
DELETE FROM items;

-- SEMENTES DE ITENS (RECURSOS + PRODUTOS DE PROFISSÕES)
INSERT INTO items (code, name, item_type, rarity, stackable, tradable, sellable_to_shop, base_value, metadata_json) VALUES

-- [RECURSOS NATURAIS E MATERIAIS BASE - JA EXISTENTES]
('erva_espiritual_comum', 'Erva Espiritual Comum', 'material', 'Comum', 1, 1, 1, 10, '{"description": "Traços fracos de Qi."}'),
('flor_nevoa', 'Flor da Névoa', 'material', 'Incomum', 1, 1, 1, 35, '{"description": "Essência úmida para pílulas."}'),
('loto_sangue', 'Lótus de Sangue', 'material', 'Incomum', 1, 1, 1, 50, '{"description": "Poder curativo latente."}'),
('ginseng_fogo', 'Ginseng de Fogo Seco', 'material', 'Raro', 1, 1, 1, 120, '{"description": "Calor concentrado."}'),
('grama_vento_uivante', 'Grama do Vento Uivante', 'material', 'Raro', 1, 1, 1, 150, '{"description": "Leveza espiritual."}'),
('cogumelo_fantasma', 'Cogumelo Ilusório Fantasma', 'material', 'Raro', 1, 1, 1, 180, '{"description": "Essência alucinógena."}'),
('fruta_dragao_azure', 'Fruta Menor do Dragão Azure', 'material', 'Épico', 1, 1, 1, 500, '{"description": "Fortalece meridianos."}'),
('flor_gelo_milenar', 'Flor de Gelo Milenar', 'material', 'Épico', 1, 1, 1, 650, '{"description": "Frio absoluto."}'),
('raiz_alma_partida', 'Raiz da Alma Partida', 'material', 'Lendário', 1, 1, 1, 2000, '{"description": "Cura feridas na alma."}'),
('erva_estelar_divina', 'Grama Estelar Imaculada', 'material', 'Celestial', 1, 1, 1, 8000, '{"description": "Luz das estrelas pura."}'),
('minerio_ferro_negro', 'Minério de Ferro Negro', 'material', 'Comum', 1, 1, 1, 15, '{"description": "Resistente e pesado."}'),
('cobre_espiritual', 'Cobre Espiritual', 'material', 'Incomum', 1, 1, 1, 60, '{"description": "Condutor de Qi."}'),
('prata_lunar', 'Prata Lunar Bruta', 'material', 'Raro', 1, 1, 1, 200, '{"description": "Brilho noturno purificador."}'),
('cristal_fogo', 'Cristal de Fogo Estilhaçado', 'material', 'Incomum', 1, 1, 1, 80, '{"description": "Fragmento ígneo."}'),
('jade_fria', 'Fragmento de Jade Fria', 'material', 'Raro', 1, 1, 1, 200, '{"description": "Calmante mental."}'),
('aco_estelar', 'Aço Estelar', 'material', 'Raro', 1, 1, 1, 250, '{"description": "Metal de alta pressão."}'),
('ouro_purpura', 'Ouro Púrpura Profundo', 'material', 'Épico', 1, 1, 1, 800, '{"description": "Nobreza espiritual."}'),
('ferro_meteoro', 'Ferro de Meteoro Caído', 'material', 'Épico', 1, 1, 1, 1200, '{"description": "Densidade sideral."}'),
('essencia_terra', 'Essência Pura da Terra', 'material', 'Lendário', 1, 1, 1, 3500, '{"description": "Coração da montanha."}'),
('cristal_caos', 'Cristal do Caos Primordial', 'material', 'Celestial', 1, 1, 1, 10000, '{"description": "Leis da criação."}'),
('osso_besta', 'Osso de Besta Selvagem', 'material', 'Comum', 1, 1, 1, 8, '{"description": "Base para forja e alquimia."}'),
('carne_besta', 'Carne de Besta Espiritual', 'material', 'Comum', 1, 1, 1, 12, '{"description": "Nutritiva com Qi."}'),
('sangue_lobo_sombra', 'Frasco de Sangue do Lobo Sombrio', 'material', 'Incomum', 1, 1, 1, 45, '{"description": "Tinta para talismãs."}'),
('garra_urso', 'Garra de Urso Terrestre', 'material', 'Incomum', 1, 1, 1, 55, '{"description": "Dura como rocha."}'),
('escama_serpente_fogo', 'Escama da Serpente de Fogo', 'material', 'Raro', 1, 1, 1, 150, '{"description": "Retém calor extremo."}'),
('pena_aguia_vento', 'Pena da Águia do Vento', 'material', 'Raro', 1, 1, 1, 160, '{"description": "Leveza absoluta."}'),
('chifre_rinoceronte', 'Chifre de Rinoceronte de Ferro', 'material', 'Épico', 1, 1, 1, 600, '{"description": "Resistência massiva."}'),
('nucleo_besta_baixo', 'Núcleo de Besta (Baixo Nível)', 'core', 'Raro', 1, 1, 1, 300, '{"description": "Energia vital comum."}'),
('nucleo_besta_medio', 'Núcleo de Besta (Médio Nível)', 'core', 'Épico', 1, 1, 1, 1500, '{"description": "Qi condensado."}'),
('sangue_fenix_impuro', 'Gota de Sangue de Fênix Impuro', 'material', 'Lendário', 1, 1, 1, 5000, '{"description": "Poder de renascimento."}'),

-- [EQUIPAMENTOS BASE]
('espada_ferro_negro', 'Espada de Ferro Negro', 'weapon', 'Comum', 0, 1, 1, 150, '{"attack": 10}'),
('lanca_madeira_ferro', 'Lança de Madeira de Ferro', 'weapon', 'Comum', 0, 1, 1, 140, '{"attack": 12}'),
('sabre_vento_cortante', 'Sabre do Vento Cortante', 'weapon', 'Incomum', 0, 1, 1, 350, '{"attack": 25}'),
('arco_osso_besta', 'Arco de Osso de Besta', 'weapon', 'Incomum', 0, 1, 1, 320, '{"attack": 22}'),
('espada_gelida_lua', 'Espada Gélida da Lua Fria', 'weapon', 'Raro', 0, 1, 1, 900, '{"attack": 55}'),
('manto_discípulo', 'Manto de Discípulo', 'armor', 'Comum', 0, 1, 1, 120, '{"defense": 5}'),
('armadura_couro_lobo', 'Armadura de Couro de Lobo', 'armor', 'Comum', 0, 1, 1, 180, '{"defense": 12}'),
('veste_seda_espiritual', 'Veste de Seda Espiritual', 'armor', 'Incomum', 0, 1, 1, 400, '{"defense": 18}'),
('armadura_escamas_fogo', 'Peitoral de Escamas de Fogo', 'armor', 'Raro', 0, 1, 1, 950, '{"defense": 45}'),
('manto_sombras', 'Manto Oculto das Sombras', 'armor', 'Épico', 0, 1, 1, 2200, '{"defense": 60}'),

-- [CONSUMÍVEIS BASE]
('pilula_recuperacao_menor', 'Pílula de Recuperação Menor', 'consumable', 'Comum', 1, 1, 1, 50, '{"hp_reg": 30}'),
('pilula_qi_menor', 'Pílula de Qi Menor', 'consumable', 'Incomum', 1, 1, 1, 100, '{"qi_reg": 25}'),
('pilula_vigor_sanguineo', 'Pílula do Vigor Sanguíneo', 'consumable', 'Incomum', 1, 1, 1, 120, '{"stamina_reg": 30}'),
('pilula_alma_clara', 'Elixir da Mente Clara', 'consumable', 'Raro', 1, 1, 1, 350, '{"soul_reg": 20}'),
('pilula_purificacao_ossea', 'Pílula de Purificação Óssea', 'consumable', 'Raro', 1, 1, 1, 500, '{"talent_exp": 100}'),
('pilula_yang_ardente', 'Pílula Yang Ardente', 'consumable', 'Épico', 1, 1, 1, 1200, '{"fire_buff": 10}'),
('pilula_yin_extrema', 'Pílula Yin Extrema', 'consumable', 'Épico', 1, 1, 1, 1200, '{"ice_buff": 10}'),
('pilula_falsa_morte', 'Pílula da Falsa Morte', 'consumable', 'Lendário', 1, 1, 1, 4500, '{"stealth": 100}'),
('pilula_avanco_espiritual', 'Pílula do Avanço Espiritual', 'consumable', 'Lendário', 1, 1, 1, 5000, '{"breakthrough_bonus": 5}'),
('pilula_reversao_inferior', 'Pílula de Reversão Inferior', 'consumable', 'Celestial', 1, 1, 1, 15000, '{"reroll": "clan"}'),

-- [NOVOS ITENS PRODUZIDOS POR PROFISSÕES]
('lâmina_estelar_nova', 'Lâmina de Aço Estelar', 'weapon', 'Épico', 0, 1, 1, 2500, '{"attack": 120}'),
('escudo_purpura_novo', 'Escudo de Ouro Púrpura', 'armor', 'Épico', 0, 1, 1, 2800, '{"defense": 150}'),
('armadura_meteoro_nova', 'Armadura Meteórica', 'armor', 'Lendário', 0, 1, 1, 8000, '{"defense": 400}'),
('adaga_caos_nova', 'Adaga do Caos', 'weapon', 'Celestial', 0, 1, 1, 25000, '{"attack": 1200}'),
('bolsa_espacial_menor', 'Bolsa Espacial Menor', 'utility', 'Incomum', 0, 1, 1, 500, '{"slots": 10}'),
('bolsa_espacial_media', 'Bolsa Espacial Média', 'utility', 'Raro', 0, 1, 1, 1500, '{"slots": 25}'),
('bolsa_espacial_maior', 'Bolsa Espacial Maior', 'utility', 'Épico', 0, 1, 1, 5000, '{"slots": 60}'),
('manto_vento_novo', 'Manto do Vento Uivante', 'armor', 'Raro', 0, 1, 1, 1200, '{"agility": 15}'),
('cinto_bestial_novo', 'Cinto de Força Bestial', 'utility', 'Incomum', 0, 1, 1, 600, '{"strength": 8}'),
('botas_fogo_novo', 'Botas de Escamas Térmicas', 'armor', 'Raro', 0, 1, 1, 1300, '{"fire_res": 20}'),
('botas_gelo_novo', 'Botas do Caminhar Frio', 'armor', 'Raro', 0, 1, 1, 1300, '{"ice_res": 20}'),
('veste_imperial_nova', 'Veste Imperial de Ouro', 'armor', 'Épico', 0, 1, 1, 4500, '{"prestige": 50}'),
('fita_alma_nova', 'Fita de Prender Cabelo (Alma)', 'utility', 'Lendário', 0, 1, 1, 9000, '{"soul_power": 30}'),
('manto_caos_novo', 'Manto Imaculado do Caos', 'armor', 'Celestial', 0, 1, 1, 30000, '{"all_res": 50}'),
('fio_espiritual_novo', 'Rolo de Fio Espiritual', 'material', 'Comum', 1, 1, 1, 50, '{"description": "Usado em tecelagem."}'),
('espeto_bestial_novo', 'Espeto de Carne Bestial', 'food', 'Comum', 1, 1, 1, 40, '{"buff": "strength_1"}'),
('sopa_clara_nova', 'Sopa Revigorante Clara', 'food', 'Comum', 1, 1, 1, 45, '{"buff": "qi_regen_1"}'),
('sopa_sangue_nova', 'Sopa de Sangue (Vigor)', 'food', 'Incomum', 1, 1, 1, 100, '{"buff": "hp_regen_2"}'),
('cha_nevoa_novo', 'Chá de Flor de Névoa', 'food', 'Comum', 1, 1, 1, 50, '{"buff": "perception_1"}'),
('cha_loto_novo', 'Chá do Lótus Vermelho', 'food', 'Incomum', 1, 1, 1, 120, '{"buff": "fire_atk_2"}'),
('ginseng_assado_novo', 'Ginseng Assado no Cristal', 'food', 'Raro', 1, 1, 1, 400, '{"buff": "fire_atk_3"}'),
('salada_vento_nova', 'Salada do Vento Leve', 'food', 'Raro', 1, 1, 1, 350, '{"buff": "agility_3"}'),
('cozido_urso_novo', 'Cozido de Pata de Urso', 'food', 'Raro', 1, 1, 1, 450, '{"buff": "phys_def_3"}'),
('vinho_fantasma_novo', 'Vinho de Cogumelo Fantasma', 'food', 'Épico', 1, 1, 1, 1500, '{"buff": "soul_atk_4"}'),
('banquete_dragao_novo', 'Banquete do Dragão Azure', 'food', 'Épico', 1, 1, 1, 3000, '{"buff": "all_stats_4"}'),
('raspadinha_gelo_nova', 'Raspadinha de Gelo Milenar', 'food', 'Raro', 1, 1, 1, 400, '{"buff": "ice_atk_3"}'),
('cha_alma_novo', 'Chá Repousante da Alma', 'food', 'Lendário', 1, 1, 1, 6000, '{"buff": "soul_regen_5"}'),
('ensopado_fenix_novo', 'Ensopado de Carne de Fênix', 'food', 'Lendário', 1, 1, 1, 8000, '{"buff": "revive_1"}'),
('nectar_estelar_novo', 'Néctar Estelar Absoluto', 'food', 'Celestial', 1, 1, 1, 20000, '{"buff": "immortality_6"}'),
('talisma_fogo_novo', 'Talismã de Fogo', 'talisman', 'Comum', 1, 1, 1, 80, '{"effect": "fire_damage"}'),
('talisma_gelo_novo', 'Talismã de Gelo', 'talisman', 'Comum', 1, 1, 1, 80, '{"effect": "ice_damage"}'),
('talisma_vento_novo', 'Talismã de Vento Rápido', 'talisman', 'Incomum', 1, 1, 1, 200, '{"effect": "speed_up"}'),
('selo_terra_novo', 'Selo de Peso da Terra', 'talisman', 'Incomum', 1, 1, 1, 250, '{"effect": "gravity"}'),
('selo_ilusao_novo', 'Selo de Ilusão Fantasma', 'talisman', 'Raro', 1, 1, 1, 800, '{"effect": "confuse"}'),
('talisma_protecao_novo', 'Talismã de Proteção Maior', 'talisman', 'Raro', 1, 1, 1, 900, '{"effect": "barrier"}'),
('talisma_explosivo_novo', 'Talismã de Fogo Explosivo', 'talisman', 'Épico', 1, 1, 1, 2500, '{"effect": "aoe_fire"}'),
('selo_supressao_novo', 'Selo de Supressão do Dragão', 'talisman', 'Épico', 1, 1, 1, 3000, '{"effect": "seal"}'),
('selo_sangue_novo', 'Selo de Sangue Devorador', 'talisman', 'Épico', 1, 1, 1, 3500, '{"effect": "lifesteal"}'),
('talisma_ocultador_novo', 'Talismã Ocultador de Aura', 'talisman', 'Lendário', 1, 1, 1, 7000, '{"effect": "invisibility"}'),
('selo_caos_novo', 'Selo do Caos Descendente', 'talisman', 'Celestial', 1, 1, 1, 25000, '{"effect": "annihilate"}'),
('pergaminho_retorno_novo', 'Pergaminho de Retorno Estelar', 'utility', 'Celestial', 1, 1, 1, 15000, '{"effect": "teleport_home"}'),
('tinta_espiritual_nova', 'Tinta Espiritual Purificada', 'material', 'Incomum', 1, 1, 1, 150, '{"description": "Usada por escribas."}'),
('bandeira_formacao_nova', 'Bandeira de Formação Básica', 'formation', 'Comum', 0, 1, 1, 300, '{"effect": "area_qi"}'),
('disco_coleta_qi_novo', 'Disco de Coleta de Qi', 'formation', 'Incomum', 0, 1, 1, 800, '{"effect": "qi_regen_area"}'),
('barreira_fogo_nova', 'Barreira de Fogo Protetora', 'formation', 'Raro', 0, 1, 1, 2500, '{"effect": "fire_dmg_area"}'),
('matriz_gelo_nova', 'Matriz de Gelo Congelante', 'formation', 'Raro', 0, 1, 1, 2500, '{"effect": "slow_area"}'),
('olho_matriz_novo', 'Olho da Matriz Espiritual', 'utility', 'Épico', 0, 1, 1, 6000, '{"effect": "reveal_area"}'),
('bandeira_ilusao_nova', 'Bandeira de Ilusão Sombria', 'formation', 'Épico', 0, 1, 1, 7000, '{"effect": "hide_area"}'),
('matriz_espada_nova', 'Matriz da Espada Estelar', 'formation', 'Lendário', 0, 1, 1, 15000, '{"effect": "atk_area"}'),
('disco_terra_novo', 'Disco de Proteção da Terra', 'formation', 'Lendário', 0, 1, 1, 14000, '{"effect": "def_area"}'),
('pilar_dragao_novo', 'Pilar de Supressão do Dragão', 'formation', 'Épico', 0, 1, 1, 8000, '{"effect": "seal_area"}'),
('matriz_fenix_nova', 'Matriz do Renascimento da Fênix', 'formation', 'Celestial', 0, 1, 1, 40000, '{"effect": "heal_area"}'),
('nucleo_caos_novo', 'Núcleo de Formação do Caos', 'material', 'Celestial', 1, 1, 1, 12000, '{"description": "Coração de formações."}'),
('luz_guia_nova', 'Luz de Guia Espiritual', 'utility', 'Incomum', 1, 1, 1, 200, '{"effect": "no_ambush"}'),
('esqueleto_marionete_novo', 'Esqueleto de Marionete', 'material', 'Comum', 0, 1, 1, 500, '{"description": "Base para autômatos."}'),
('esqueleto_ferro_novo', 'Esqueleto de Ferro Negro', 'material', 'Incomum', 0, 1, 1, 1200, '{"description": "Base resistente."}'),
('nucleo_motriz_novo', 'Núcleo Motriz', 'material', 'Incomum', 1, 1, 1, 800, '{"description": "Motor de marionete."}'),
('marionete_lobo_nova', 'Marionete Lobo de Madeira', 'puppet', 'Raro', 0, 1, 1, 4500, '{"pet_stats": "medium"}'),
('marionete_aranha_nova', 'Marionete Aranha de Prata', 'puppet', 'Épico', 0, 1, 1, 12000, '{"pet_stats": "high"}'),
('braco_urso_novo', 'Braço de Urso Esmagador', 'utility', 'Raro', 0, 1, 1, 2000, '{"attack_bonus": 40}'),
('armadura_marionete_nova', 'Armadura de Marionete', 'armor', 'Épico', 0, 1, 1, 9000, '{"def_bonus": 100}'),
('marionete_dragao_nova', 'Marionete Dragão de Ferro', 'puppet', 'Lendário', 0, 1, 1, 45000, '{"pet_stats": "legendary"}'),
('marionete_anjo_nova', 'Marionete Anjo Caído', 'puppet', 'Celestial', 0, 1, 1, 150000, '{"pet_stats": "divine"}'),
('junta_marionete_nova', 'Peça de Juntas Lubrificadas', 'material', 'Comum', 1, 1, 1, 100, '{"description": "Repara marionetes."}'),
('fio_alma_novo', 'Fio de Controle da Alma', 'utility', 'Lendário', 1, 1, 1, 8000, '{"puppet_control": 100}'),
('racao_bestial_nova', 'Ração Bestial', 'food', 'Comum', 1, 1, 1, 30, '{"pet_xp": 50}'),
('pilula_crescimento_nova', 'Pílula de Crescimento Bestial', 'consumable', 'Incomum', 1, 1, 1, 400, '{"pet_level": 1}'),
('selo_domesticacao_novo', 'Selo de Domesticação Menor', 'utility', 'Incomum', 1, 1, 1, 600, '{"catch_rate": 10}'),
('coleira_besta_nova', 'Coleira de Retenção de Qi', 'utility', 'Raro', 0, 1, 1, 1500, '{"pet_loyalty": 5}'),
('isca_besta_nova', 'Isca de Carne Perfumada', 'utility', 'Raro', 1, 1, 1, 800, '{"attract_rate": 20}'),
('essencia_linhagem_nova', 'Essência Despertadora', 'consumable', 'Épico', 1, 1, 1, 10000, '{"pet_evolution": 1}'),
('selo_domesticacao_maior', 'Selo de Domesticação Maior', 'utility', 'Lendário', 1, 1, 1, 15000, '{"catch_rate": 50}'),
('armadura_pet_nova', 'Armadura Bestial Leve', 'armor', 'Raro', 0, 1, 1, 3000, '{"pet_def": 50}'),
('ninho_incubacao_novo', 'Ninho de Incubação Acelerado', 'utility', 'Lendário', 0, 1, 1, 20000, '{"hatch_speed": 2.0}'),
('cristal_evolucao_novo', 'Cristal de Evolução do Caos', 'material', 'Celestial', 1, 1, 1, 50000, '{"description": "Evolução suprema."}');
